apiVersion: v1
kind: Pod
metadata:
  name: nodehelloworld.example.com
  labels:
    apps: helloworld
spec:
  containers:
  - name: k8s-demo
    image: robo9111/k8s-demo
    ports:
    - containerPort: 3000